# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

workflows:
  build:
    jobs:
      - build:
          context:
            - docker_push

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: ./build.sh
      - run: docker images
